apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ppython 
  janus-idp.io/tekton: ppython
  backstage.io/kubernetes-id: ppython
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppython
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  