apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ppython
  janus-idp.io/tekton: ppython
  backstage.io/kubernetes-id: ppython
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ppython
resources:
- deployment.yaml
- route.yaml
- service.yaml
