apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ppython
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ppython 
  name: ppython
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ppython 
